#!/usr/bin/env zsh

alias l="exa -1 --color=always --group-directories-first --all"
alias ll="exa --binary --group --header --all --long --links --classify --group-directories-first"
alias ls="exa --git --color=always --group-directories-first"
