#!/usr/bin/env zsh

alias l="eza -1 --color=always --group-directories-first --all"
alias ll="eza --binary --group --header --all --long --links --classify --group-directories-first"
alias ls="eza --color=always --group-directories-first"
alias pip=pip3
alias python=python3
alias rimraf="rm -rf"
alias open=xdg-open
alias myip="curl -sSfL -w '\n' https://ifconfig.me/ip"
alias github-auto-merge="gh pr list --json number --jq .[].number | xargs -I{} sh -c 'gh pr review {} --approve; gh pr merge {} --squash'"
alias ride="open \"\$(find \$(pwd) -maxdepth 3 -name '*.sln' | head -n 1)\""
