#!/usr/bin/env zsh

### zsh-snap installer
if [[ ! -f "$HOME/.zsh/zsh-snap/znap.zsh" ]]; then
  print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}marlonrichert/zsh-snap%F{220})…%f"
  command mkdir -p "$HOME/.zsh" && command chmod g-rwX "$HOME/.zsh"
  HOME= command git clone --verbose --depth 1 https://github.com/marlonrichert/zsh-snap "$HOME/.zsh/zsh-snap" && \
    print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
    print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zsh/zsh-snap/znap.zsh"
### End of zsh-snap installer

znap source powerlevel10k

znap source ohmyzsh plugins/gitfast

znap source asdf

znap source asdf completions

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
znap source zsh-syntax-highlighting

znap eval thefuck 'thefuck --alias'
znap eval kubectl 'kubectl completion zsh'

zstyle \
  ':completion:*:complete:(cd|pushd):*' tag-order \
  'local-directories named-directories'
zstyle ':completion:*' menu yes select

cdpath=($HOME/git/code $HOME/git/work)

HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=$HOME/.zsh_history
DOTFILES=$HOME/git/code/dotfiles

# Set up the prompt

setopt hist_ignore_all_dups
setopt hist_expire_dups_first
setopt hist_reduce_blanks
setopt inc_append_history
setopt share_history

# Keybinding
bindkey -e
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

[[ ! -f "$DOTFILES/zsh/aliases" ]] || source "$DOTFILES/zsh/aliases"
[[ ! -f "$DOTFILES/zsh/p10k.zsh" ]] || source "$DOTFILES/zsh/p10k.zsh"
