#!/usr/bin/env zsh

# module_path+=( "/home/joseph/.zinit/bin/zmodules/Src" )
# zmodload zdharma/zplugin

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
  print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
  command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
  command git clone https://github.com/zdharma-continuum/zinit "$HOME/.zinit/bin" && \
    print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
    print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit depth"1" light-mode for \
  zdharma-continuum/z-a-as-monitor \
  zdharma-continuum/zinit-annex-patch-dl \
  zdharma-continuum/zinit-annex-bin-gem-node \
  zdharma-continuum/z-a-rust \
  laggardkernel/zsh-thefuck \
  romkatv/zsh-defer \

# Zsh plugins

zinit depth"1" wait lucid for \
  atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
    zdharma-continuum/fast-syntax-highlighting \
  blockf \
    zsh-users/zsh-completions \
  atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions \
    zdharma-continuum/history-search-multi-word \

# Binaries

zinit as"null" wait lucid from"gh-r" for \
  mv"krew-linux_amd64 -> krew" bpick"krew.tar.gz" sbin atclone"./krew install krew && ./krew update" atpull"%atclone" has"kubectl" kubernetes-sigs/krew \
  mv"bin/exa* -> exa" sbin ogham/exa \

# completions

zinit depth"1" wait lucid for \
  pick"asdf.sh" @asdf-vm/asdf \

zinit depth"1" wait lucid atload="zicompinit; zicdreplay" blockf for \
  OMZ::plugins/kubectl/kubectl.plugin.zsh \
  OMZ::plugins/git/git.plugin.zsh \
  https://github.com/jetersen/ohmyzsh/raw/helm-cache/plugins/helm/helm.plugin.zsh \
  https://github.com/jetersen/ohmyzsh/raw/feature/gh-plugin/plugins/gh/gh.plugin.zsh \

zstyle \
  ':completion:*:complete:(cd|pushd):*' tag-order \
  'local-directories named-directories'
zstyle ':completion:*' menu yes select

cdpath=($HOME/git/code $HOME/git/work)

HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=$HOME/.zsh_history
DOTFILES=$HOME/git/code/dotfiles

# Set up the prompt

setopt hist_ignore_all_dups
setopt hist_expire_dups_first
setopt hist_reduce_blanks
setopt inc_append_history
setopt share_history

# Keybinding
bindkey -e
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

[[ ! -f "$DOTFILES/zsh/aliases" ]] || source "$DOTFILES/zsh/aliases"

if [ -z "$WSL_DISTRO_NAME" ]; then
  zsh-defer -c 'eval "$(oh-my-posh --init --shell zsh --config ~/.jetersen.omp.json)"'
else
  zsh-defer -c 'eval "$(oh-my-posh-wsl --init --shell zsh --config ~/.jetersen.omp.json)"'
fi
