#!/usr/bin/env zsh

# module_path+=( "/home/joseph/.zinit/bin/zmodules/Src" )
# zmodload zdharma/zplugin

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

if [ -n "$BREW_PREFIX" ]; then
  zinit fpath -f "$BREW_PREFIX/share/zsh/site-functions"
fi

export SESSIONDEFAULTUSER="$USER"

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit depth"1" light-mode for \
  zdharma-continuum/zinit-annex-patch-dl \
  NICHOLAS85/z-a-linkbin \
  laggardkernel/zsh-thefuck \
  romkatv/zsh-defer \

# Zsh plugins

zinit depth"1" wait lucid for \
  atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
    zdharma-continuum/fast-syntax-highlighting \
  blockf \
    zsh-users/zsh-completions \
  atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions \
    zdharma-continuum/history-search-multi-word \

# Binaries

zinit light-mode lucid as'null' from"gh-r" for \
  lbin updatecli/updatecli \
  mv"posh* -> oh-my-posh" lbin JanDeDobbeleer/oh-my-posh \

# completions

zinit depth"1" wait lucid atload="zicompinit; zicdreplay" blockf for \
  OMZ::plugins/git/git.plugin.zsh \

zstyle \
  ':completion:*:complete:(cd|pushd):*' tag-order \
  'local-directories named-directories'
zstyle ':completion:*' menu yes select

cdpath=($HOME/git/code $HOME/git/work)

HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=$HOME/.zsh_history
DOTFILES=$HOME/git/code/dotfiles

# Set up the prompt

setopt hist_ignore_all_dups
setopt hist_expire_dups_first
setopt hist_reduce_blanks
setopt inc_append_history
setopt share_history

# Keybinding
bindkey -e
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
# Bind Delete key to delete a character
bindkey "^[[3~" delete-char

# Bind Shift + Delete to delete the entire word under the cursor
bindkey -s "^[[3;2~" '\eb\ed'

[[ ! -f "$DOTFILES/zsh/aliases" ]] || source "$DOTFILES/zsh/aliases"

zsh-defer -c 'eval "$(oh-my-posh --init --shell zsh --config ~/.jetersen.omp.json)"'

type -p direnv &>/dev/null && eval "$(direnv hook zsh)"
